
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConversionMontantEuroToDH")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConversionMontantEuroToDH", targetNamespace = "http://ws/", className = "proxy.ConversionMontantEuroToDH")
    @ResponseWrapper(localName = "ConversionMontantEuroToDHResponse", targetNamespace = "http://ws/", className = "proxy.ConversionMontantEuroToDHResponse")
    @Action(input = "http://ws/BanqueService/ConversionMontantEuroToDHRequest", output = "http://ws/BanqueService/ConversionMontantEuroToDHResponse")
    public double conversionMontantEuroToDH(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param code
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompteDetails", targetNamespace = "http://ws/", className = "proxy.GetCompteDetails")
    @ResponseWrapper(localName = "getCompteDetailsResponse", targetNamespace = "http://ws/", className = "proxy.GetCompteDetailsResponse")
    @Action(input = "http://ws/BanqueService/getCompteDetailsRequest", output = "http://ws/BanqueService/getCompteDetailsResponse")
    public Compte getCompteDetails(
        @WebParam(name = "code", targetNamespace = "")
        int code);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listCpts", targetNamespace = "http://ws/", className = "proxy.ListCpts")
    @ResponseWrapper(localName = "listCptsResponse", targetNamespace = "http://ws/", className = "proxy.ListCptsResponse")
    @Action(input = "http://ws/BanqueService/listCptsRequest", output = "http://ws/BanqueService/listCptsResponse")
    public List<Compte> listCpts();

}
